spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username : root
    password : root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true